import type { PromptContextEnvelope } from "@/context/PromptContextTypes";

/** A single message stored in the primary thread or an other-chats file. */
export interface TelegramStoredMessage {
  /** Stable local UUID assigned on append. Optional only for backward compat with pre-existing rows. */
  local_id?: string;
  /** Telegram update_id — only for source "telegram"; used for idempotent append. */
  update_id?: number;
  /** Telegram message ID. */
  message_id?: number;
  chat_id: number;
  /** Display name: Telegram first name for telegram-source, "You" for obsidian-source. */
  sender_name: string;
  sender_type: "user" | "bot";
  /**
   * Message origin marker:
   * - "telegram": delivered via Telegram transport
   * - "obsidian": created locally in the plugin (including local-only bot replies)
   */
  source: "telegram" | "obsidian";
  /** Plain text, or "[photo]" / "[document]" etc. for media messages. */
  text: string;
  /** Vault-relative path to the saved media file (e.g. .copilot/telegram-state/media/…). */
  mediaPath?: string;
  /** MIME type of the media file (e.g. "image/jpeg", "application/pdf"). */
  mediaType?: string;
  /** Original filename for documents; undefined for photos/voice. */
  mediaName?: string;
  /** Optional structured prompt context generated by the Telegram composer. */
  contextEnvelope?: PromptContextEnvelope;
  /** Optional pre-serialized prompt text used by legacy consumers. */
  processedText?: string;
  /** Unix seconds from Telegram; Date.now() for obsidian-source. */
  date: number;
  /** Date.now() when appended to the store. Used for reset_at filtering. */
  stored_at: number;
}

/**
 * Transient in-memory state for a Telegram AI reply that is currently being generated.
 * This is never persisted to disk; it only powers live UI updates and streaming bubbles.
 */
export interface TelegramReplyState {
  /** Chat currently receiving the reply. */
  chatId: number;
  /** Stable ID shared by the temporary streaming row and the final persisted bot message. */
  streamingMessageId: string;
  /** Latest partial assistant text emitted by the chain. */
  partialText: string;
  /** Optional loader label shown before or alongside partial output. */
  loadingMessage: string;
  /** Date.now() when the transient reply state was created. */
  startedAt: number;
}

/** Persisted meta.json shape. */
export interface TelegramMeta {
  bot_id: number;
  offset: number;
  /** chatId of the designated primary chat; null until first inbound message. */
  primary_chat_id: number | null;
  /** stored_at threshold — messages with stored_at < reset_at are hidden from view. */
  reset_at: number;
}

/** Telegram Bot API Update object (minimal subset we care about). */
export interface TelegramUpdate {
  update_id: number;
  message?: TelegramMessage;
}

/** One size variant of a Telegram photo. */
export interface TelegramPhotoSize {
  file_id: string;
  file_unique_id: string;
  width: number;
  height: number;
  file_size?: number;
}

/** Telegram document (any file type). */
export interface TelegramDocument {
  file_id: string;
  file_unique_id: string;
  file_name?: string;
  mime_type?: string;
  file_size?: number;
}

/** Telegram voice message (OGG audio). */
export interface TelegramVoice {
  file_id: string;
  file_unique_id: string;
  duration: number;
  mime_type?: string;
  file_size?: number;
}

/** Telegram audio file. */
export interface TelegramAudio {
  file_id: string;
  file_unique_id: string;
  duration: number;
  title?: string;
  file_name?: string;
  mime_type?: string;
  file_size?: number;
}

/** Telegram video file. */
export interface TelegramVideo {
  file_id: string;
  file_unique_id: string;
  width: number;
  height: number;
  duration: number;
  file_name?: string;
  mime_type?: string;
  file_size?: number;
}

/** Telegram Bot API Message object (minimal subset). */
export interface TelegramMessage {
  message_id: number;
  from?: TelegramUser;
  chat: TelegramChat;
  date: number;
  text?: string;
  caption?: string;
  photo?: TelegramPhotoSize[];
  sticker?: unknown;
  document?: TelegramDocument;
  audio?: TelegramAudio;
  video?: TelegramVideo;
  voice?: TelegramVoice;
}

export interface TelegramUser {
  id: number;
  first_name: string;
  last_name?: string;
  username?: string;
  is_bot?: boolean;
}

export interface TelegramChat {
  id: number;
  type: "private" | "group" | "supergroup" | "channel";
  title?: string;
  first_name?: string;
  last_name?: string;
  username?: string;
}

/** Response from getMe. */
export interface TelegramBotInfo {
  id: number;
  first_name: string;
  username: string;
  is_bot: true;
}
